version: '3.9'

services:
  libro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro_libro
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_libros
    environment:
      MYSQL_ROOT_PASSWORD: "ali_12345"
      MYSQL_DATABASE: "librosdb"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: